### ISSUE TITLE
[Bug]: Doesn't work with Laravel 11

### ISSUE THREAD

**Issue by PovilasKorop** [Safemood/discountify#16]
### What happened?

I wanted to shoot a review video but installation on Laravel 11 didn't work.

```
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires safemood/discountify * -> satisfiable by safemood/discountify[0.1.0, 0.3.1, 0.4.0, 1.0.0, ..., 1.4.0].
    - safemood/discountify[0.1.0, ..., 0.4.0, 1.0.0, ..., 1.4.0] require illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., v10.48.4] but these were not loaded, likely because it conflicts with another require.
```

My guess: it seems like you've pushed the changes to support Laravel 11 but maybe haven't released a new version?

### How to reproduce the bug

Just run `composer require safemood/discountify` on a new Laravel 11 project.

### Package Version

Latest

### PHP Version

8.2

### Laravel Version

11.0

**Comment by Safemood** [comment]
Hey @PovilasKorop,

Thanks for flagging the issue! I'll tackle the Laravel 11 compatibility straight away.

You're right that the update is already available in the main branch. However, there's a version constraint on illuminate/contracts (^10.0) that needs adjusting.

Your videos always hit the mark, and I'm definitely looking forward to this one too. Thanks for stopping by!

**Comment by PovilasKorop** [comment]
@Safemood great to hear, that was a fast fix! Will get back to shooting a review, will be published in a few weeks.
