### ISSUE TITLE
[Bug]: Conditions with date always return TRUE?

### ISSUE THREAD

**Issue by PovilasKorop** [Safemood/discountify#19]
### What happened?

The discount is applied, although the date condition is false.

### How to reproduce the bug

Trying an example from readme:

```
            ->add([
                [
                    'slug' => 'promo_early_spring_sale_2024',
                    'condition' => fn ($items) => now()->between(
                        Carbon::createFromDate(2024, 3, 1),
                        Carbon::createFromDate(2024, 3, 15)->addDays(7)
                    ),
                    'discount' => 15,
                ],
```

Doing it on March 31, so date condition is false, but number is still applied.

### Package Version

1.4

### PHP Version

8.2

### Laravel Version

11.0

### Notes

P.S. Not relevant to the issue itself, but my plan was to shoot a review, but with two CRUCIAL (in my opinion) bugs about calculations, just can't trust other calculations to be correct. 

So I'm canceling the idea for a review, I hope you understand.
Still reporting the two most important bugs found, hope it helps you.

**Comment by Safemood** [comment]
Hi @PovilasKorop 

Appreciate you reporting those critical bugs! While I extensively test the package, I overlooked these particular cases. They've been fixed now, with additional test cases added. Your feedback is truly valuable, thank you for your feedback.
