### ISSUE TITLE
[Feature]: Support flat cost based discounts as well instead of just percentage based

### ISSUE THREAD

**Issue by iamroi** [Safemood/discountify#27]
### What happened?

Thanks for the great package.

As the title says, is it possible to add support for flat cost discounts?

Also is it possible to use `moneyphp/money` instead of `float`s everywhere?

> "If I had a dime for every time I've seen someone use FLOAT to store currency, I'd have $999.997634" -- [Bill Karwin](https://twitter.com/billkarwin/status/347561901460447232) 

### How to reproduce the bug

There is no bug

### Package Version

latest

### PHP Version

latest supported

### Laravel Version

latest supported

### Which operating systems does with happen with?

macOS

**Comment by iamroi** [comment]
Hey @Safemood Thanks for your response and supporting different types of discounts!

Regarding the alternate solution, could you please confirm if we can make below code work as we need to do `/`?

```
    public function calculateFinalTotal(): float
    {
        $total = $this->calculateTotalWithTaxes();
        $discountRate = $this->discountRate();
        $discountedTotal = $total * (1 - $discountRate / 100);

        return max(0, $discountedTotal);
    }
```

**Comment by Safemood** [comment]
Hi @iamroi 

Yes, you can override that by extending the Discountify class, but I think you can also simply convert flat-based discounts to percentage-based ones, which will have the same results.

something like this : 

```php
<?php

// Function to convert a flat discount to a percentage discount
function convertFlatToPercentage($flatDiscount, $originalPrice) {
    return $originalPrice == 0 ? 0 : ($flatDiscount / $originalPrice) * 100;
}


// Example items
$items = [
    ['id' => '1', 'quantity' => 2, 'price' => 50],
    ['id' => '2', 'quantity' => 1, 'price' => 100],
];

// Set items to Discountify  
Discountify::setItems($items);

$original_price = Discountify::subtotal() 

// Define your flat discount 
$flat_discount = 20; // update this to check 

// Calculate the percentage discount equivalent
$percentage_discount = convertFlatToPercentage($flat_discount, $original_price);

// Define the condition (using a hypothetical Condition class)
Condition::define('more_than_2_products_10', fn (array $items) => count($items) > 2, $percentage_discount);

// Calculate the total after applying discounts
$total = Discountify::total();

// Output the total
echo "Total after discount: $" . $total;

```
