### ISSUE TITLE
[Question]: Condition by promotion or wholesale from database

### ISSUE THREAD

**Issue by yashiroiori** [Safemood/discountify#9]
### What happened?

It's posible to make discount or pay X quantity products like promotion??
For example: promotion 3X2, buy 3 products but only pay 2

Other case are load tabular from database
For example: wholesale price like for 1 to 5 products $10, 6 to 10 products $8, etc, etc but take condition from database for reason the customer config own prices tabular or promotions

### How to reproduce the bug

Not bug

### Package Version

1.3.0

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

macOS, Linux

**Comment by Safemood** [comment]
Thank you for reaching out, I appreciate your interest. 
Currently, the package doesn't support "3X2" promotions.
For range pricing, I will include it in the next release.
Regarding the database, I am already planning to abstract the storage driver, allowing options like 'in_memory,' 'database,' or custom drivers. I hope that answers your question.

**Comment by yashiroiori** [comment]
> Thank you for reaching out, I appreciate your interest. Currently, the package doesn't support "3X2" promotions. For range pricing, I will include it in the next release. Regarding the database, I am already planning to abstract the storage driver, allowing options like 'in_memory,' 'database,' or custom drivers. I hope that answers your question.

I wait next version, excelent work 👍

**Comment by Safemood** [comment]
Hi @yashiroiori,

After reconsideration, I've decided to hold off on implementing range pricing as it would be a breaking change at this time. Instead, it's possible to use:

```php
Condition::define('2_5_products_10', fn (array $items) => count($items) >= 2 && count($items) <= 5, 10); // 10% discount for 2 to 5 products

Condition::define('6_10_products_10', fn (array $items) => count($items) >= 6 && count($items) <= 10, 15); // 15% discount for 6 to 10 products
```

Let me know if you have any questions or suggestions. Your feedback is welcome!

**Comment by yashiroiori** [comment]
> Hi @yashiroiori,
> 
> After reconsideration, I've decided to hold off on implementing range pricing as it would be a breaking change at this time. Instead, it's possible to use:
> 
> ```
> Condition::define('2_5_products_10', fn (array $items) => count($items) >= 2 && count($items) <= 5, 10); // 10% discount for 2 to 5 products
> 
> Condition::define('6_10_products_10', fn (array $items) => count($items) >= 6 && count($items) <= 10, 15); // 15% discount for 6 to 10 products
> ```
> 
> Let me know if you have any questions or suggestions. Your feedback is welcome!

Great news, have an idea how implement using database?? The goal are to use into Sale Order and the users can define a tabular for prices or promotion price to offer discount into sale to customers, I would like to contribute this implementation and the prices wholesale, use Laravel with inertiajs and react

Sorry for my bad english

**Comment by Safemood** [comment]
Your English is perfectly fine. Glad to hear you found a solution!
I will avoid any breaking change, but I'll still work on abstracting the storage driver in future releases.
